In [7]:
#importing the packages
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [26]:
#reading the dataset
ds = pd.read_csv('../datasets/equake_clean.csv')
ds.head()

Unnamed: 0                                     name          equake_near  \
0           0  San Francisco-Oakland Bay Bridge, 1936     1989, Loma Prieta   
1           1         San Francisco-Oakland Bay Bridge  Northern California   
2           2         San Francisco-Oakland Bay Bridge             Bay Area   
3           3         San Francisco-Oakland Bay Bridge    1km N of Piedmont   
4           4         San Francisco-Oakland Bay Bridge   2km SE of Berkeley   

  material type  age of bridge bridge type  magnitude  \
0             I             53         III        6.9   
1             I             57         III        4.7   
2             I             67         III        4.0   
3             I             79         III        4.0   
4             I             82         III        4.4   

   d to epicenter in miles  damaged Damage level  
0                     59.9        1        0_0_1  
1                     50.0        0        1_0_0  
2                      6.9        0        1_0_0  
3                      6.3        0        1_0_0  
4                      5.4        0        1_0_0

In [27]:
ds['damaged'].value_counts()

0    228
1     21
Name: damaged, dtype: int64

In [28]:
#selecting columns for classification
X = ds.iloc[:, 3:-2].values
y = ds.iloc[:, -2].values

In [29]:
print(X)

[['I' 53 'III' 6.9 59.9]
 ['I' 57 'III' 4.7 50.0]
 ['I' 67 'III' 4.0 6.9]
 ...
 ['I' 17 'I' 6.6 56.3]
 ['I' 53 'I' 4.5 26.6]
 ['I' 54 'I' 4.4 45.7]]


In [30]:
print(y)

[1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0
 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [31]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0,2])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 53 6.9 59.9]
 [1.0 0.0 0.0 ... 57 4.7 50.0]
 [1.0 0.0 0.0 ... 67 4.0 6.9]
 ...
 [1.0 0.0 1.0 ... 17 6.6 56.3]
 [1.0 0.0 1.0 ... 53 4.5 26.6]
 [1.0 0.0 1.0 ... 54 4.4 45.7]]


In [32]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0
 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [33]:
#splitting the dataset.
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [34]:
#converting the quantity into scalar form.
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [35]:
print(X_train)

[[ 0.81992006 -0.81992006  0.57154761 ... -0.903155   -0.57932134
  -0.44563327]
 [-1.21963109  1.21963109  0.57154761 ...  2.88899276 -0.57932134
  -1.05252434]
 [ 0.81992006 -0.81992006 -1.74963553 ...  1.64157573 -1.2681037
   0.86555114]
 ...
 [ 0.81992006 -0.81992006 -1.74963553 ... -1.00294836  0.28165661
   0.43847965]
 [ 0.81992006 -0.81992006  0.57154761 ...  1.1925056  -0.66541914
  -1.07125555]
 [-1.21963109  1.21963109  0.57154761 ... -0.00501474  1.40092794
  -0.50931937]]


In [36]:
print(y_train)

[0 0 0 0 1 0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 0]


In [37]:
#importing classification packages.
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier as KNN
from sklearn.ensemble import VotingClassifier
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from xgboost import XGBClassifier

SEED = 1

In [38]:
#classification
lr = LogisticRegression(random_state=SEED)
knn = KNN()
xg = XGBClassifier()
dt = DecisionTreeClassifier(random_state=SEED)
rf = RandomForestClassifier(random_state=SEED)

# Define a list called classifier that contains the tuples (classifier_name, classifier)
classifiers = [('Logistic Regression', lr),
               ('K Nearest Neighbours', knn),
               ('Classification Tree', dt),
               ('Forest', rf),
               ('XGB', xg)]

In [39]:
# Iterate over the defined list of tuples containing the classifiers
for clf_name, clf in classifiers:
    #fit clf to the training set
    clf.fit(X_train, y_train)
    # Predict the labels of the test set
    y_pred = clf.predict(X_test)
    
    print('{:s} : {:s}'.format(clf_name, classification_report(y_test, y_pred)))

Logistic Regression :               precision    recall  f1-score   support

           0       0.96      0.98      0.97        46
           1       0.67      0.50      0.57         4

    accuracy                           0.94        50
   macro avg       0.81      0.74      0.77        50
weighted avg       0.93      0.94      0.94        50

K Nearest Neighbours :               precision    recall  f1-score   support

           0       0.94      1.00      0.97        46
           1       1.00      0.25      0.40         4

    accuracy                           0.94        50
   macro avg       0.97      0.62      0.68        50
weighted avg       0.94      0.94      0.92        50

Classification Tree :               precision    recall  f1-score   support

           0       0.98      0.98      0.98        46
           1       0.75      0.75      0.75         4

    accuracy                           0.96        50
   macro avg       0.86      0.86      0.86        50
weighte

/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [40]:
vc = VotingClassifier(estimators=classifiers)
# Fit 'vc' to the traing set and predict test set labels
vc.fit(X_train, y_train)
y_pred = vc.predict(X_test)
# Evaluate the test-set accuracy of 'vc'
print('Voting Classifier: {:s}'.format(classification_report(y_test, y_pred)))

Voting Classifier:               precision    recall  f1-score   support

           0       0.96      0.98      0.97        46
           1       0.67      0.50      0.57         4

    accuracy                           0.94        50
   macro avg       0.81      0.74      0.77        50
weighted avg       0.93      0.94      0.94        50



/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
