In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
ds = pd.read_csv('../datasets/equake_clean.csv')
ds.head()

Unnamed: 0                                     name          equake_near  \
0           0  San Francisco-Oakland Bay Bridge, 1936     1989, Loma Prieta   
1           1         San Francisco-Oakland Bay Bridge  Northern California   
2           2         San Francisco-Oakland Bay Bridge             Bay Area   
3           3         San Francisco-Oakland Bay Bridge    1km N of Piedmont   
4           4         San Francisco-Oakland Bay Bridge   2km SE of Berkeley   

  material type  age of bridge bridge type  magnitude  \
0             I             53         III        6.9   
1             I             57         III        4.7   
2             I             67         III        4.0   
3             I             79         III        4.0   
4             I             82         III        4.4   

   d to epicenter in miles  damaged  I  II  III  
0                     59.9        1  0   0    1  
1                     50.0        0  1   0    0  
2                      6.9        0  1   0    0  
3                      6.3        0  1   0    0  
4                      5.4        0  1   0    0

In [3]:
X = ds.iloc[:, 3:-4].values
y = ds.iloc[:, 8: ].values

In [4]:
print(X)

[['I' 53 'III' 6.9 59.9]
 ['I' 57 'III' 4.7 50.0]
 ['I' 67 'III' 4.0 6.9]
 ...
 ['I' 17 'I' 6.6 56.3]
 ['I' 53 'I' 4.5 26.6]
 ['I' 54 'I' 4.4 45.7]]


In [5]:
print(y)

[[1 0 0 1]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [1 0 0 1]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [1 0 0 1]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [1 0 1 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [1 0 0 1]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [1 0 1 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [1 0 0 1]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [1 0 0 1]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [1 0 0 1]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [1 0 0 1]
 [0 1 0 0]

In [6]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0, 2])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [7]:
print(X)

[[1.0 0.0 0.0 ... 53 6.9 59.9]
 [1.0 0.0 0.0 ... 57 4.7 50.0]
 [1.0 0.0 0.0 ... 67 4.0 6.9]
 ...
 [1.0 0.0 1.0 ... 17 6.6 56.3]
 [1.0 0.0 1.0 ... 53 4.5 26.6]
 [1.0 0.0 1.0 ... 54 4.4 45.7]]


In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
print(X_train)

[[ 0.88795357 -0.88795357 -1.82361767 ...  1.68284273 -1.24284247
   1.37193343]
 [ 0.88795357 -0.88795357 -1.82361767 ...  1.99041766  1.72421521
   2.80101334]
 [-1.12618501  1.12618501  0.54836056 ... -0.00881935  1.3751496
  -0.51252686]
 ...
 [ 0.88795357 -0.88795357 -1.82361767 ... -0.82901915 -0.80651046
  -0.8679457 ]
 [-1.12618501  1.12618501  0.54836056 ... -1.18785656 -0.98104327
  -0.95309813]
 [-1.12618501  1.12618501  0.54836056 ... -0.72649418  2.24781362
   1.01281232]]


In [11]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [12]:
y_pred = classifier.predict(X_test)

In [20]:
from sklearn.metrics import precision_score
precision_score(y_test, y_pred, average='weighted')

0.942512077294686

In [21]:
from sklearn.metrics import f1_score
f1_score(y_test, y_pred, average='weighted')

0.9269323671497585

In [22]:
from sklearn.metrics import recall_score
recall_score(y_test, y_pred, average='weighted')

0.927536231884058